// <auto-generated>
// This code is generated by csbindgen.
// DON'T CHANGE THIS DIRECTLY.
// </auto-generated>
#pragma warning disable CS8500
#pragma warning disable CS8981
using System;
using System.Runtime.InteropServices;


namespace SparrowEngine.Native
{
    internal static unsafe partial class NativeMethods
    {
        const string __DllName = "sparrow_engine";





        /// <summary>
        ///  Create a new engine from a JSON config string. Returns null on error.
        ///
        ///  # Safety
        ///  `config_json` must be a valid, non-null, null-terminated UTF-8 string.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "sparrow_engine_engine_new", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void* sparrow_engine_engine_new(byte* config_json);

        /// <summary>
        ///  Free an engine. All models loaded through this engine become invalid.
        ///
        ///  # Safety
        ///  `engine` must be a pointer returned by `sparrow_engine_engine_new`, or null (no-op).
        /// </summary>
        [DllImport(__DllName, EntryPoint = "sparrow_engine_engine_free", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void sparrow_engine_engine_free(void* engine);

        /// <summary>
        ///  Load a model from a TOML manifest file path. Returns null on error.
        ///
        ///  # Safety
        ///  - `engine` must be a valid engine pointer.
        ///  - `manifest_path` must be a valid, non-null, null-terminated UTF-8 string.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "sparrow_engine_load_model", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void* sparrow_engine_load_model(void* engine, byte* manifest_path);

        /// <summary>
        ///  Load a model by its ID from the model directory. Returns null on error.
        ///
        ///  Idempotent / lazy: if the model is already loaded, returns a fresh handle
        ///  to the existing ORT session (no re-creation). Mirrors the lazy-load
        ///  contract exposed by the HTTP `/v1/models/load` and `/v1/detect`+`/v1/classify`+
        ///  `/v1/audio` endpoints and the `sparrow-engine-python` package — calling twice with
        ///  the same id does not invalidate previously-issued handles.
        ///
        ///  # Safety
        ///  - `engine` must be a valid engine pointer.
        ///  - `model_id` must be a valid, non-null, null-terminated UTF-8 string.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "sparrow_engine_load_model_by_id", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void* sparrow_engine_load_model_by_id(void* engine, byte* model_id);

        /// <summary>
        ///  Unload a model and free its resources.
        ///
        ///  # Safety
        ///  `model` must be a pointer returned by `sparrow_engine_load_model` / `sparrow_engine_load_model_by_id`, or null.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "sparrow_engine_unload_model", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void sparrow_engine_unload_model(void* model);

        /// <summary>
        ///  Load a pipeline from a TOML manifest. Returns 0 on success, -1 on error.
        ///
        ///  # Safety
        ///  - `engine` must be a valid engine pointer.
        ///  - `manifest_path` must be a valid, non-null, null-terminated UTF-8 string.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "sparrow_engine_load_pipeline", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int sparrow_engine_load_pipeline(void* engine, byte* manifest_path);

        /// <summary>
        ///  Load a pipeline by its ID from the model directory. Returns 0 on success, -1 on error.
        ///
        ///  # Safety
        ///  - `engine` must be a valid engine pointer.
        ///  - `pipeline_id` must be a valid, non-null, null-terminated UTF-8 string.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "sparrow_engine_load_pipeline_by_id", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int sparrow_engine_load_pipeline_by_id(void* engine, byte* pipeline_id);

        /// <summary>
        ///  Unload a pipeline by ID. Returns 0 on success, -1 on error.
        ///
        ///  # Safety
        ///  - `engine` must be a valid engine pointer.
        ///  - `pipeline_id` must be a valid, non-null, null-terminated UTF-8 string.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "sparrow_engine_unload_pipeline", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int sparrow_engine_unload_pipeline(void* engine, byte* pipeline_id);

        /// <summary>
        ///  Run detection on an encoded image buffer (JPEG/PNG). Returns null on error.
        ///
        ///  # Safety
        ///  - `model` must be a valid model pointer.
        ///  - `image` must point to `len` bytes of encoded image data.
        ///  - `opts` may be null (use defaults).
        /// </summary>
        [DllImport(__DllName, EntryPoint = "sparrow_engine_detect", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern SparrowEngineDetections* sparrow_engine_detect(void* model, byte* image, nuint len, SparrowEngineDetectOpts* opts);

        /// <summary>
        ///  Run detection on a raw pixel buffer. Returns null on error.
        ///
        ///  # Safety
        ///  - `model` must be a valid model pointer.
        ///  - `pixels` must point to `h * stride` bytes of pixel data.
        ///  - `opts` may be null (use defaults).
        /// </summary>
        [DllImport(__DllName, EntryPoint = "sparrow_engine_detect_raw", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern SparrowEngineDetections* sparrow_engine_detect_raw(void* model, byte* pixels, uint w, uint h, uint stride, uint format, SparrowEngineDetectOpts* opts);

        /// <summary>
        ///  Run batch detection on multiple encoded images. Returns 0 on success, -1 on error.
        ///  The callback is invoked per-image with detection results.
        ///  Images are processed in batches (default 4) for higher GPU throughput.
        ///
        ///  See `SparrowEngineDetectBatchCallback` for the per-image callback contract and
        ///  additive-extension rules (both enforced by the Phase 3.5 S5/S6 handoff).
        ///
        ///  # Safety
        ///  - `model` must be a valid model pointer.
        ///  - `images` must point to `image_count` `SparrowEngineImageBuffer` structs.
        ///  - `opts` may be null (use defaults).
        ///  - `callback` must be valid for the duration of this call.
        ///  - `batch_size` of 0 uses the default (4).
        /// </summary>
        [DllImport(__DllName, EntryPoint = "sparrow_engine_detect_batch", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int sparrow_engine_detect_batch(void* model, SparrowEngineImageBuffer* images, nuint image_count, SparrowEngineDetectOpts* opts, nuint batch_size, delegate* unmanaged[Cdecl]<nuint, SparrowEngineDetections*, void*, void> callback, void* user_data);

        /// <summary>
        ///  Run classification on an encoded image buffer (JPEG/PNG). Returns null on error.
        ///
        ///  # Safety
        ///  - `model` must be a valid model pointer.
        ///  - `image` must point to `len` bytes of encoded image data.
        ///  - `opts` may be null (use defaults).
        /// </summary>
        [DllImport(__DllName, EntryPoint = "sparrow_engine_classify", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern SparrowEngineClassifyResult* sparrow_engine_classify(void* model, byte* image, nuint len, SparrowEngineClassifyOpts* opts);

        /// <summary>
        ///  Run a pipeline (detect → classify) on an encoded image. Returns null on error.
        ///
        ///  # Safety
        ///  - `engine` must be a valid engine pointer.
        ///  - `pipeline_id` must be a valid, non-null, null-terminated UTF-8 string.
        ///  - `image` must point to `len` bytes of encoded image data.
        ///  - `detect_opts` and `classify_opts` may be null (use defaults).
        /// </summary>
        [DllImport(__DllName, EntryPoint = "sparrow_engine_run_pipeline", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern SparrowEnginePipelineResult* sparrow_engine_run_pipeline(void* engine, byte* pipeline_id, byte* image, nuint len, SparrowEngineDetectOpts* detect_opts, SparrowEngineClassifyOpts* classify_opts);

        /// <summary>
        ///  Run audio detection on a WAV file. Returns null on error.
        ///
        ///  # Safety
        ///  - `model` must be a valid model pointer (audio model with mel spectrogram preprocessing).
        ///  - `audio_path` must be a valid, non-null, null-terminated UTF-8 path to a WAV file.
        ///  - `opts` may be null (use defaults).
        /// </summary>
        [DllImport(__DllName, EntryPoint = "sparrow_engine_detect_audio", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern SparrowEngineAudioResult* sparrow_engine_detect_audio(void* model, byte* audio_path, SparrowEngineAudioDetectOpts* opts);

        /// <summary>
        ///  Run audio detection on a WAV file with V2 top-K classes. Returns null on error.
        ///
        ///  # Safety
        ///  - `model` must be a valid model pointer (audio model with mel spectrogram preprocessing).
        ///  - `audio_path` must be a valid, non-null, null-terminated UTF-8 path to a WAV file.
        ///  - `opts` may be null (use defaults).
        /// </summary>
        [DllImport(__DllName, EntryPoint = "sparrow_engine_detect_audio_v2", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern SparrowEngineAudioResult_v2* sparrow_engine_detect_audio_v2(void* model, byte* audio_path, SparrowEngineAudioDetectOpts* opts);

        /// <summary>
        ///  Run audio detection with per-segment streaming callback.
        ///
        ///  CPU callback cadence is per-segment: the callback is invoked immediately
        ///  after each detected segment is produced, allowing the caller to update
        ///  progress incrementally.
        ///
        ///  Note: the GPU flavor of this symbol fires callbacks post-detect (after the
        ///  full chunk loop completes) rather than per-segment. Callers writing
        ///  flavor-agnostic UI code should not assume per-segment cadence; see the
        ///  matching doc-comment in `sparrow-engine-gpu/src/ffi.rs`.
        ///
        ///  Returns the complete result (same as `sparrow_engine_detect_audio`).
        ///
        ///  # Safety
        ///  - `model` must be a valid model pointer.
        ///  - `audio_path` must be a valid, non-null, null-terminated UTF-8 path.
        ///  - `opts` may be null (use defaults).
        ///  - `callback` must be a valid function pointer for the duration of this call.
        ///  - `user_data` is passed through to the callback unchanged.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "sparrow_engine_detect_audio_streaming", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern SparrowEngineAudioResult* sparrow_engine_detect_audio_streaming(void* model, byte* audio_path, SparrowEngineAudioDetectOpts* opts, delegate* unmanaged[Cdecl]<SparrowEngineAudioSegment*, void*, void> callback, void* user_data);

        /// <summary>
        ///  Free a `SparrowEngineAudioResult` returned by `sparrow_engine_detect_audio`.
        ///
        ///  # Safety
        ///  `ptr` must be a pointer returned by `sparrow_engine_detect_audio`, or null.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "sparrow_engine_audio_result_free", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void sparrow_engine_audio_result_free(SparrowEngineAudioResult* ptr);

        /// <summary>
        ///  Free a `SparrowEngineAudioResult_v2` returned by `sparrow_engine_detect_audio_v2`.
        ///
        ///  # Safety
        ///  `ptr` must be a pointer returned by `sparrow_engine_detect_audio_v2`, or null.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "sparrow_engine_audio_result_v2_free", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void sparrow_engine_audio_result_v2_free(SparrowEngineAudioResult_v2* ptr);

        /// <summary>
        ///  Free a `SparrowEngineDetections` returned by `sparrow_engine_detect` or `sparrow_engine_detect_raw`.
        ///
        ///  # Safety
        ///  `ptr` must be a pointer returned by `sparrow_engine_detect`/`sparrow_engine_detect_raw`, or null.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "sparrow_engine_detections_free", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void sparrow_engine_detections_free(SparrowEngineDetections* ptr);

        /// <summary>
        ///  Free a `SparrowEngineClassifyResult` returned by `sparrow_engine_classify`.
        ///
        ///  # Safety
        ///  `ptr` must be a pointer returned by `sparrow_engine_classify`, or null.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "sparrow_engine_classify_result_free", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void sparrow_engine_classify_result_free(SparrowEngineClassifyResult* ptr);

        /// <summary>
        ///  Free a `SparrowEnginePipelineResult` returned by `sparrow_engine_run_pipeline`.
        ///
        ///  # Safety
        ///  `ptr` must be a pointer returned by `sparrow_engine_run_pipeline`, or null.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "sparrow_engine_pipeline_result_free", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void sparrow_engine_pipeline_result_free(SparrowEnginePipelineResult* ptr);

        /// <summary>
        ///  Free a string returned by `sparrow_engine_list_models` or `sparrow_engine_health`.
        ///
        ///  # Safety
        ///  `ptr` must be a pointer returned by a sparrow-engine function that allocates strings, or null.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "sparrow_engine_free_string", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void sparrow_engine_free_string(byte* ptr);

        /// <summary>
        ///  List loaded models as a JSON string. Returns null on error.
        ///  Caller must free with `sparrow_engine_free_string`.
        ///
        ///  # Safety
        ///  `engine` must be a valid engine pointer.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "sparrow_engine_list_models", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern byte* sparrow_engine_list_models(void* engine);

        /// <summary>
        ///  Return engine health as a JSON string. Returns null on error.
        ///  Caller must free with `sparrow_engine_free_string`.
        ///
        ///  # Safety
        ///  `engine` must be a valid engine pointer.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "sparrow_engine_health", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern byte* sparrow_engine_health(void* engine);

        /// <summary>
        ///  Return the last error message for this thread, or null if no error.
        ///  The returned pointer is valid until the next FFI call on the same thread.
        ///
        ///  # Safety
        ///  Thread-safe. Returned pointer must not be freed by the caller.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "sparrow_engine_last_error", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern byte* sparrow_engine_last_error();

        /// <summary>
        ///  Compute SHA-256 hash of a file. Returns hex string or null on error.
        ///  Caller must free with `sparrow_engine_hash_result_free`.
        ///
        ///  # Safety
        ///  `path` must be a valid, non-null, null-terminated UTF-8 string.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "sparrow_engine_hash_file", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern byte* sparrow_engine_hash_file(byte* path);

        /// <summary>
        ///  Free a hash string returned by `sparrow_engine_hash_file`.
        ///
        ///  # Safety
        ///  `ptr` must be a pointer returned by `sparrow_engine_hash_file`, or null.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "sparrow_engine_hash_result_free", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void sparrow_engine_hash_result_free(byte* ptr);

        /// <summary>
        ///  Classify image as day or night. Returns result by value.
        ///  On error: status=-1, check `sparrow_engine_last_error`.
        ///
        ///  # Safety
        ///  `image` must point to `len` bytes of encoded image data (JPEG/PNG).
        /// </summary>
        [DllImport(__DllName, EntryPoint = "sparrow_engine_day_night", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern SparrowEngineDayNightResultC sparrow_engine_day_night(byte* image, nuint len);

        /// <summary>
        ///  Compute mean image brightness [0,255]. Returns -1.0 on error.
        ///
        ///  # Safety
        ///  `image` must point to `len` bytes of encoded image data (JPEG/PNG).
        /// </summary>
        [DllImport(__DllName, EntryPoint = "sparrow_engine_image_brightness", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern float sparrow_engine_image_brightness(byte* image, nuint len);

        /// <summary>
        ///  Verify a model's ONNX file against manifest checksums.
        ///  Returns null on error. Caller must free with `sparrow_engine_verify_result_free`.
        ///
        ///  # Safety
        ///  `model_dir` and `model_id` must be valid, non-null, null-terminated UTF-8 strings.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "sparrow_engine_verify_model", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern SparrowEngineVerifyResultC* sparrow_engine_verify_model(byte* model_dir, byte* model_id);

        /// <summary>
        ///  Free a `SparrowEngineVerifyResultC` returned by `sparrow_engine_verify_model` or `sparrow_engine_engine_verify_model`.
        ///
        ///  # Safety
        ///  `ptr` must be a pointer returned by `sparrow_engine_verify_model`/`sparrow_engine_engine_verify_model`, or null.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "sparrow_engine_verify_result_free", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void sparrow_engine_verify_result_free(SparrowEngineVerifyResultC* ptr);

        /// <summary>
        ///  Verify a model using the engine's model directory. Returns null on error.
        ///  Caller must free with `sparrow_engine_verify_result_free`.
        ///
        ///  # Safety
        ///  - `engine` must be a valid engine pointer.
        ///  - `model_id` must be a valid, non-null, null-terminated UTF-8 string.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "sparrow_engine_engine_verify_model", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern SparrowEngineVerifyResultC* sparrow_engine_engine_verify_model(void* engine, byte* model_id);

        /// <summary>
        ///  Get model info as JSON string. Searches loaded models first, then disk.
        ///  Returns null on error. Caller must free with `sparrow_engine_free_string`.
        ///
        ///  # Safety
        ///  - `engine` must be a valid engine pointer.
        ///  - `model_id` must be a valid, non-null, null-terminated UTF-8 string.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "sparrow_engine_engine_model_info", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern byte* sparrow_engine_engine_model_info(void* engine, byte* model_id);

        /// <summary>
        ///  List all available models (on disk) as JSON array with extended info.
        ///  Includes version, description, and checksums. Returns null on error.
        ///  Caller must free with `sparrow_engine_free_string`.
        ///
        ///  # Safety
        ///  `engine` must be a valid engine pointer.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "sparrow_engine_engine_list_models_extended", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern byte* sparrow_engine_engine_list_models_extended(void* engine);

        /// <summary>
        ///  Returns a pointer to a static, null-terminated UTF-8 string with the
        ///  sparrow-engine-cpu crate version (matches `[package].version` in
        ///  `sparrow-engine-cpu/Cargo.toml`). Caller MUST NOT free.
        ///
        ///  Phase D B-12: useful for installer / Studio Local / brew `test do` smoke
        ///  tests — a zero-arg, zero-allocation entry point that proves DLL load +
        ///  symbol resolution without spinning up an engine. Byte-for-byte mirror of
        ///  the GPU FFI surface (G5 acceptance gate enforces CPU/GPU symbol parity).
        ///
        ///  # Safety
        ///  Thread-safe. Returned pointer is valid for the lifetime of the process.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "sparrow_engine_version", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern byte* sparrow_engine_version();


    }

    /// <summary>
    ///  Axis-aligned bounding box, normalized [0,1], xyxy format.
    /// </summary>
    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct SparrowEngineBBox
    {
        public float x_min;
        public float y_min;
        public float x_max;
        public float y_max;
    }

    /// <summary>
    ///  Single detection result. `label` pointer valid until `sparrow_engine_detections_free()`.
    /// </summary>
    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct SparrowEngineDetection
    {
        public SparrowEngineBBox bbox;
        public byte* label;
        public uint label_id;
        public float confidence;
    }

    /// <summary>
    ///  Detection result set from a single `sparrow_engine_detect()` / `sparrow_engine_detect_raw()` call.
    /// </summary>
    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct SparrowEngineDetections
    {
        public SparrowEngineDetection* data;
        public nuint len;
        public uint image_width;
        public uint image_height;
    }

    /// <summary>
    ///  Single classification prediction.
    /// </summary>
    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct SparrowEngineClassification
    {
        public byte* label;
        public uint label_id;
        public float confidence;
    }

    /// <summary>
    ///  Classification result from a single `sparrow_engine_classify()` call.
    /// </summary>
    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct SparrowEngineClassifyResult
    {
        public byte* label;
        public uint label_id;
        public float confidence;
        public SparrowEngineClassification* top_results;
        public nuint top_results_len;
        public uint image_width;
        public uint image_height;
        public float processing_time_ms;
    }

    /// <summary>
    ///  A pipeline detection: detection + optional classification.
    /// </summary>
    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct SparrowEnginePipelineDetection
    {
        public SparrowEngineDetection detection;
        [MarshalAs(UnmanagedType.U1)] public bool has_classification;
        public SparrowEngineClassification classification;
    }

    /// <summary>
    ///  Pipeline result from `sparrow_engine_run_pipeline()`.
    /// </summary>
    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct SparrowEnginePipelineResult
    {
        public byte* pipeline_id;
        public SparrowEnginePipelineDetection* data;
        public nuint len;
        public uint image_width;
        public uint image_height;
        public float processing_time_ms;
    }

    /// <summary>
    ///  Detection inference options. Zero = use default.
    /// </summary>
    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct SparrowEngineDetectOpts
    {
        public float confidence_threshold;
        public uint max_detections;
    }

    /// <summary>
    ///  Classification inference options. Zero = use default.
    /// </summary>
    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct SparrowEngineClassifyOpts
    {
        public uint top_k;
    }

    /// <summary>
    ///  A single detected audio segment.
    /// </summary>
    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct SparrowEngineAudioSegment
    {
        public float start_time_s;
        public float end_time_s;
        public float confidence;
    }

    /// <summary>
    ///  Audio detection result from `sparrow_engine_detect_audio`.
    /// </summary>
    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct SparrowEngineAudioResult
    {
        public SparrowEngineAudioSegment* data;
        public nuint len;
        public float duration_s;
        public uint sample_rate;
        public float processing_time_ms;
    }

    /// <summary>
    ///  V2 (Perch 2 + future multi-class classifiers): per-class entry for top-K output.
    ///  `label` is a borrowed pointer into the result's CString arena; valid until the
    ///  SparrowEngineAudioResult_v2 is freed via sparrow_engine_audio_result_v2_free.
    ///  `label` may be null when the model has no label for this index.
    /// </summary>
    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct SparrowEngineAudioClass
    {
        public uint class_idx;
        public byte* label;
        public float probability;
    }

    /// <summary>
    ///  V2 audio segment: same V1 fields plus a top-K classes array.
    ///  `classes` is a borrowed pointer into the result; valid for the lifetime of the result.
    /// </summary>
    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct SparrowEngineAudioSegment_v2
    {
        public float start_time_s;
        public float end_time_s;
        public float confidence;
        public SparrowEngineAudioClass* classes;
        public nuint classes_len;
    }

    /// <summary>
    ///  V2 audio detection result. Free with sparrow_engine_audio_result_v2_free.
    /// </summary>
    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct SparrowEngineAudioResult_v2
    {
        public SparrowEngineAudioSegment_v2* data;
        public nuint len;
        public float duration_s;
        public uint sample_rate;
        public float processing_time_ms;
    }

    /// <summary>
    ///  Audio detection options. Zero = use manifest default.
    /// </summary>
    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct SparrowEngineAudioDetectOpts
    {
        public float confidence_threshold;
        public float segment_duration_s;
        public float segment_stride_s;
    }

    /// <summary>
    ///  A single image buffer for batch detection.
    /// </summary>
    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct SparrowEngineImageBuffer
    {
        public byte* data;
        public nuint len;
    }

    /// <summary>
    ///  Day/night result. Returned by value (small struct).
    /// </summary>
    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct SparrowEngineDayNightResultC
    {
        /// <summary>
        ///  0 = success, -1 = error (check `sparrow_engine_last_error`).
        /// </summary>
        public int status;
        /// <summary>
        ///  1 = day, 0 = night. Undefined if status != 0.
        /// </summary>
        public int is_day;
        /// <summary>
        ///  Mean brightness [0,255]. -1.0 if status != 0.
        /// </summary>
        public float brightness;
    }

    /// <summary>
    ///  Model verification result. Freed by `sparrow_engine_verify_result_free`.
    /// </summary>
    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct SparrowEngineVerifyResultC
    {
        /// <summary>
        ///  0=Ok, 1=NoChecksum, 2=SizeMismatch, 3=ChecksumMismatch.
        ///  On error, `sparrow_engine_verify_model` returns null (call `sparrow_engine_last_error` for detail).
        /// </summary>
        public int status;
        /// <summary>
        ///  Detail message. Null if status=0 or status=1.
        /// </summary>
        public byte* detail;
    }



}
