"""HuggingFace Hub upload for pw-tools.

Uploads the following files to the specified HF repository:
  - <model>.onnx              (the ONNX model)
  - <model>.toml              (the manifest)
  - labels.txt / labels.json  (if referenced in manifest)
  - README.md                 (auto-generated model card)

Uses the huggingface_hub Python client (>=0.20 required for CommitOperationAdd).
"""

from __future__ import annotations

import os
import sys
import tempfile
from pathlib import Path
from typing import Any

if sys.version_info >= (3, 11):
    import tomllib
else:
    try:
        import tomllib  # type: ignore[no-redef]
    except ImportError:
        import tomli as tomllib  # type: ignore[no-redef,import-not-found]


# ---------------------------------------------------------------------------
# Model card generation
# ---------------------------------------------------------------------------

_MODEL_CARD_TEMPLATE = """\
---
{yaml_frontmatter}
---

# {name}

{description}

## Model Details

| Field | Value |
|-------|-------|
| Model ID | `{model_id}` |
| Task | {task} |
| Format | ONNX (opset {opset}) |
| Version | {version} |
| License | {license} |
| Input shape | `{input_shape}` |
| Input format | {input_format} |
| SHA-256 | `{sha256}` |
| File size | {file_size_mb:.1f} MB |

## Preprocessing

```toml
{preprocessing_toml}
```

## Postprocessing

```toml
{postprocessing_toml}
```

## Labels

{labels_section}

## Usage with PytorchWildlife

```python
import pytorchwildlife as pw

model = pw.load_model("{model_id}")
results = model.predict("image.jpg")
```

## Citation

If you use this model in your research, please cite the original authors.
See the [PytorchWildlife repository](https://github.com/microsoft/CameraTraps) for details.

## Tags

{tags_list}

---

*This model card was auto-generated by `pw-tools upload`.*
"""


def _dict_to_toml_inline(d: dict[str, Any]) -> str:
    """Minimal inline TOML serialiser for the model card."""
    lines: list[str] = []
    for k, v in d.items():
        if isinstance(v, str):
            lines.append(f'{k} = "{v}"')
        elif isinstance(v, list):
            items = ", ".join(f'"{x}"' if isinstance(x, str) else str(x) for x in v)
            lines.append(f"{k} = [{items}]")
        elif isinstance(v, float):
            lines.append(f"{k} = {v}")
        elif isinstance(v, int):
            lines.append(f"{k} = {v}")
        elif isinstance(v, bool):
            lines.append(f"{k} = {'true' if v else 'false'}")
    return "\n".join(lines)


def _yaml_frontmatter(model: dict[str, Any]) -> str:
    """Generate the YAML block for the HF model card front-matter."""
    lines: list[str] = []
    lines.append("library_name: pytorchwildlife")

    task = model.get("type", "")
    hf_task_map = {
        "detection": "object-detection",
        "classification": "image-classification",
        "audio_classification": "audio-classification",
        "point_detection": "object-detection",
    }
    if hf_task := hf_task_map.get(task):
        lines.append(f"pipeline_tag: {hf_task}")

    license_id = model.get("license", "mit").lower()
    lines.append(f"license: {license_id}")

    tags = model.get("tags", [])
    if tags:
        lines.append("tags:")
        for tag in tags:
            lines.append(f"  - {tag}")
        lines.append("  - onnx")
        lines.append("  - wildlife")
    else:
        lines.append("tags:\n  - onnx\n  - wildlife")

    return "\n".join(lines)


def _build_model_card(model: dict[str, Any]) -> str:
    """Build the full README.md content for the HF model card."""
    preprocessing = model.get("preprocessing", {})
    postprocessing = model.get("postprocessing", {})

    # Labels section
    labels = model.get("labels", {})
    if labels:
        labels_md_lines = ["| Index | Label |", "|-------|-------|"]
        for idx, lbl in sorted(labels.items(), key=lambda x: int(x[0])):
            labels_md_lines.append(f"| {idx} | {lbl} |")
        labels_section = "\n".join(labels_md_lines)
    elif model.get("labels_file"):
        labels_section = f"See `{model['labels_file']}` for the full label list."
    else:
        labels_section = "No labels specified."

    tags = model.get("tags", [])
    tags_list = " ".join(f"`{t}`" for t in tags) if tags else "None"

    return _MODEL_CARD_TEMPLATE.format(
        yaml_frontmatter=_yaml_frontmatter(model),
        name=model.get("name", model.get("id", "Unknown")),
        description=model.get("description", ""),
        model_id=model.get("id", ""),
        task=model.get("type", ""),
        opset=model.get("opset_version", "unknown"),
        version=model.get("version", ""),
        license=model.get("license", ""),
        input_shape=model.get("input_shape", []),
        input_format=model.get("input_format", ""),
        sha256=model.get("sha256", ""),
        file_size_mb=model.get("file_size_bytes", 0) / (1024 * 1024),
        preprocessing_toml=_dict_to_toml_inline(preprocessing),
        postprocessing_toml=_dict_to_toml_inline(postprocessing),
        labels_section=labels_section,
        tags_list=tags_list,
    )


# ---------------------------------------------------------------------------
# Upload orchestration
# ---------------------------------------------------------------------------


def upload_to_hub(
    manifest_path: str,
    repo_id: str,
    token: str | None,
    private: bool,
    dry_run: bool,
    commit_message: str,
) -> None:
    """Upload the model bundle to HuggingFace Hub."""
    from rich.console import Console
    from rich.table import Table

    console = Console()
    mp = Path(manifest_path)

    if not mp.exists():
        console.print(f"[red]Manifest not found: {mp}[/]")
        raise SystemExit(1)

    with open(mp, "rb") as fh:
        data = tomllib.load(fh)
    model = data.get("model", {})

    # Resolve ONNX path
    onnx_name = model.get("file", "")
    if not onnx_name:
        console.print("[red]manifest [model].file is empty[/]")
        raise SystemExit(1)
    onnx_path = mp.parent / onnx_name
    if not onnx_path.exists():
        console.print(f"[red]ONNX file not found: {onnx_path}[/]")
        raise SystemExit(1)

    # Collect files to upload: (local_path, path_in_repo)
    files_to_upload: list[tuple[Path, str]] = [
        (onnx_path, onnx_name),
        (mp, mp.name),
    ]

    # Labels file
    labels_file = model.get("labels_file")
    if labels_file:
        lf_path = mp.parent / labels_file
        if lf_path.exists():
            files_to_upload.append((lf_path, labels_file))
        else:
            console.print(f"[yellow]Warning: labels_file '{labels_file}' not found — skipping[/]")

    # Generate model card
    model_card_content = _build_model_card(model)

    # Print upload plan
    table = Table(title="Upload Plan", show_lines=True)
    table.add_column("Local Path", style="cyan")
    table.add_column("Path in Repo")
    table.add_column("Size")
    for lp, rp in files_to_upload:
        size_mb = lp.stat().st_size / (1024 * 1024)
        table.add_row(str(lp), rp, f"{size_mb:.2f} MB")
    table.add_row("(generated)", "README.md", f"{len(model_card_content) / 1024:.1f} KB")
    console.print(table)

    console.print(f"\nTarget repository: [bold]{repo_id}[/]")
    if private:
        console.print("  Visibility: private")
    if dry_run:
        console.print("\n[yellow]DRY RUN — no files will be uploaded.[/]")
        return

    # Resolve HF token
    hf_token = token or os.environ.get("HF_TOKEN") or os.environ.get("HUGGINGFACE_TOKEN")
    if not hf_token:
        console.print(
            "[red]No HuggingFace token provided.[/]\n"
            "Pass --token or set the HF_TOKEN environment variable."
        )
        raise SystemExit(1)

    from huggingface_hub import CommitOperationAdd, HfApi

    api = HfApi(token=hf_token)

    # Create or confirm repo
    console.print(f"\n[bold cyan]Creating/confirming repository[/] {repo_id}")
    repo_url = api.create_repo(
        repo_id=repo_id,
        repo_type="model",
        private=private,
        exist_ok=True,
    )
    console.print(f"  Repository URL: {repo_url}")

    # Build commit operations
    operations: list[CommitOperationAdd] = []

    for lp, rp in files_to_upload:
        operations.append(
            CommitOperationAdd(
                path_in_repo=rp,
                path_or_fileobj=str(lp),
            )
        )

    # Model card
    with tempfile.NamedTemporaryFile(mode="w", suffix=".md", delete=False, encoding="utf-8") as tmp:
        tmp.write(model_card_content)
        tmp_card_path = tmp.name

    operations.append(
        CommitOperationAdd(
            path_in_repo="README.md",
            path_or_fileobj=tmp_card_path,
        )
    )

    # Commit message
    model_name = model.get("name", model.get("id", "model"))
    model_version = model.get("version", "")
    if not commit_message:
        commit_message = f"Upload {model_name} v{model_version} via pw-tools"

    console.print(f"\n[bold cyan]Committing {len(operations)} file(s)[/]")
    console.print(f"  Message: {commit_message}")

    try:
        commit_info = api.create_commit(
            repo_id=repo_id,
            repo_type="model",
            operations=operations,
            commit_message=commit_message,
        )
        console.print(f"\n[bold green]Upload complete.[/]")
        console.print(f"  Commit URL: {commit_info.commit_url}")
        console.print(f"  Model URL:  https://huggingface.co/{repo_id}")
    finally:
        # Clean up temp model card file
        Path(tmp_card_path).unlink(missing_ok=True)
